<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>12.0</LangVersion>
    <OutputType>Library</OutputType>
    <RootNamespace>OverwatchSystem</RootNamespace>
    <AssemblyName>OverwatchSystem</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ExMod.Exiled" Version="9.14.2" />
    <PackageReference Include="HintServiceMeow-Exiled" Version="5.5.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="0Harmony">
      <HintPath>..\..\..\..\source\repos\EXILED_REFERENCES\0Harmony.dll</HintPath>
    </Reference>
	<Reference Include="Assembly-CSharp">
		<HintPath>..\..\..\..\source\repos\EXILED_REFERENCES\Assembly-CSharp.dll</HintPath>
	</Reference>  
    <Reference Include="Assembly-CSharp-firstpass">
      <HintPath>..\..\..\..\source\repos\EXILED_REFERENCES\Assembly-CSharp-firstpass.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine">
      <HintPath>..\..\..\..\source\repos\EXILED_REFERENCES\UnityEngine.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>..\..\..\..\source\repos\EXILED_REFERENCES\UnityEngine.CoreModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.PhysicsModule">
      <HintPath>..\..\..\..\source\repos\EXILED_REFERENCES\UnityEngine.PhysicsModule.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>